export const projects = [
  {
    id: "water",
    title: "Water Supply Project",
    location: "Rajkot, Gujarat",
    Category: "Water Supply",
    description:
      "Executed underground water supply pipeline installation including trench excavation, DI/HDPE pipe laying, valve chamber construction, hydro testing, and commissioning across key service zones in Rajkot, Gujarat, ensuring improved water pressure and distribution efficiency.",
    images: [
      "/Water.jpg",
      "Rajkot/RJJK Work.jpeg",
      "Rajkot/RJJK Work1.jpeg",
      "Rajkot/RJJK Work2.jpeg",
      "Rajkot/RJJK Work3.jpeg",
      "Rajkot/RJJK Work4.jpeg",
      "Rajkot/RJJK Work5.jpeg",
      "Rajkot/RJK(mid).jpeg",
      "Rajkot/RJK(mid)1.jpeg",
      "Rajkot/RJK(Comp).jpeg",
      "Rajkot/RJK(Comp)1.jpeg",
      "Rajkot/RJK(Comp)2.jpeg",
      "Rajkot/RJK(Comp)3.jpeg",
      "Rajkot/RJK(Comp)4.jpeg",
    ],
  },
  {
    id: "sewage",
    title: "Sewage System Project",
    location: "Ujjain, MP",
    Category: "Sewage System",
    description:
      "Execution of an underground sewage collection network including RCC NP3 pipeline installation, manhole construction, and precise gradient alignment for efficient wastewater flow. The system was integrated with the municipal drainage network and connected to the Sewage Treatment Plant (STP). Work was carried out in active urban zones with controlled excavation, dewatering management, and complete surface restoration, in compliance with municipal engineering standards and quality protocols.",
    images: [
      "/sewer.jpg",
      "Ujjain/UJN(STR)1.jpeg",
      "Ujjain/UJN(WRK).jpeg",
      "Ujjain/UJN(WRK)2.jpeg",
      "Ujjain/UJN(WRK)3.jpeg",
      "Ujjain/UJN(WRK)5.jpeg",
      "Ujjain/UJN(WRK)6.jpeg",
      "Ujjain/UJN(CMP)1.jpeg",
      "Ujjain/UJN(WRK)1.jpeg",
      "Ujjain/UJN(WRK)7.jpeg",
      "Ujjain/UJN(WRK)8.jpeg",
      "Ujjain/UJN(CMP)2.jpeg",
      "Ujjain/UJN(CMP)3.jpeg",
    ],
  },
];
